import { createElement } from 'lwc';
import TestLWC from 'c/testLWC';

describe('c-test-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-test-lwc', {
            is: TestLWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        const h1 = element.shadowRoot.querySelector('h1').textContent;
        expect(h1).toEqual("hello");
    });
});